whoami: "api-store"
output: "grpc" # Options: console, file, grpc
level: "info"
grpc:
  address: "0.0.0.0"
  port: 50057
# file_path: "logs"
# file_name: "app.log"
log_fields:
  include_thread_id: false
  include_target: false
  include_file: false
  include_line: false
  include_timestamp: false
debug_mode:
  enabled: true
  test_interval_secs: 100
log_all_messages: false
server:
  grpc:
    host: "127.0.0.1"
    port: 50057
  http:
    host: "127.0.0.1"
    port: 5007
formatter_host: "127.0.0.1"
formatter_port: 8080
formatter_host: "0.0.0.0"  # Docker service name or hostname
